Ext.define('QS.model.QsOperations', {
	extend: 'Ext.data.Model',
	fields:
    [
        { name: 'CompanyName',              type: 'string'  },
        { name: 'StoreName',                type: 'string'  },
        { name: 'FranGroup',                type: 'string'  },
        { name: 'WeekOf',                   type: 'string'  },
        { name: 'BusinessDate',             type: 'string'  }, //, dateFormat: 'n/j h:ia'},
        { name: 'PromoAdjSales',            type: 'float'   }, 
        { name: 'NetSales',                 type: 'float'   }, 
        { name: 'CustomerCount',            type: 'float'   }, // Customer Count
        { name: 'DriveThruSales',           type: 'float'   }, // Drive Thru Sales
        //{ name: 'EmployeeHours',            type: 'float'   },
        // new, added march 20, 2012        
//        { name: 'MarketName',               type: 'string'  },
//        { name: 'DMName',                   type: 'string'  },  
        //{ name: 'StoreNumber',              type: 'int'     },
        //{ name: 'AdjustedSales',            type: 'float'   },   
        //{ name: 'AdjustedSalesLY',          type: 'float'   }, 
        { name: 'AdjustedSalesCalcTY',      type: 'float'   }, 
        //{ name: 'CustomerCountLY',          type: 'float'   }, 
        { name: 'CustomerCountCalcTY',      type: 'float'   }, 
        { name: 'CashOverShort',            type: 'float'   },   
        //{ name: 'WasteAmount',              type: 'float'   }, 
        //{ name: 'AuditTotal',               type: 'float'   },  
        //{ name: 'ManagerMeals',             type: 'float'   },    
        //{ name: 'EmplyeeMeals',             type: 'float'   },    
        //{ name: 'FreeFood',                 type: 'float'   },    
        //{ name: 'BreakfastSales',           type: 'float'   },  
        { name: 'LunchSales',               type: 'float'   },  
        { name: 'AfternoonSales',           type: 'float'   },  
        { name: 'DinnerSales',              type: 'float'   }, 
        { name: 'NightSales',               type: 'float'   },  
        //{ name: 'MidnightSales',            type: 'float'   },   
        { name: 'CloseSales',               type: 'float'   },  
        //{ name: 'SalesTax',                 type: 'float'   },    
        //{ name: 'NonFoodA',                 type: 'float'   },    
        //{ name: 'NonFoodB',                 type: 'float'   },    
        //{ name: 'KidsCredit',               type: 'float'   },  
        //{ name: 'GiftCertSNew',             type: 'float'   },    
        //{ name: 'PaidIns',                  type: 'float'   }, 
        //{ name: 'PaidOuts',                 type: 'float'   },    
        //{ name: 'DiscountAmount',           type: 'float'   },  
        //{ name: 'Deposit1',                 type: 'float'   },    
        //{ name: 'Deposit2',                 type: 'float'   },    
        //{ name: 'Deposit3',                 type: 'float'   },    
        { name: 'Deposit4',                 type: 'float'   },    
        //{ name: 'CashOnHand',               type: 'float'   },  
        //{ name: 'CashAccountabiliy',        type: 'float'   },   
        //{ name: 'VoidAmount',               type: 'float'   },  
        //{ name: 'StateTaxRate',             type: 'float'   }, 
        //{ name: 'CalculatedTax',            type: 'float'   }, 
        { name: 'Deposit5',                 type: 'float'   }, 
        { name: 'Deposit6',                 type: 'float'   }, 
        { name: 'Deposit7',                 type: 'float'   }, 
        { name: 'Deposit8',                 type: 'float'   }, 
        //{ name: 'Deposit9',                 type: 'float'   }, 
        //{ name: 'Deposit10',                type: 'float'   }, 
        //{ name: 'Deposit11',                type: 'float'   }, 
        //{ name: 'Deposit12',                type: 'float'   }, 
        //{ name: 'Deposit13',                type: 'float'   }, 
        //{ name: 'Deposit14',                type: 'float'   }, 
        //{ name: 'DayName',                  type: 'string'  }, 
        { name: 'DriveCount',               type: 'float'   }, 
        //{ name: 'AdjustedSales2Y',          type: 'float'   }, 
        //{ name: 'CustomerCount2Y',          type: 'float'   }, 
        { name: 'BreakfastCount',           type: 'float'   }, 
        //{ name: 'NetSalesLy',               type: 'float'   }, 
        //{ name: 'CreditCardPct',            type: 'float'   }, 
        //{ name: 'BreakfastSalesLY',         type: 'float'   }, 
        //{ name: 'LunchSalesLY',             type: 'float'   }, 
        //{ name: 'AfternoonSalesLY',         type: 'float'   }, 
        //{ name: 'DinnerSalesLY',            type: 'float'   }, 
        //{ name: 'NightSalesLY',             type: 'float'   }, 
        //{ name: 'CloseSalesLY',             type: 'float'   }, 
        //{ name: 'CashSales',                type: 'float'   }, 
        //{ name: 'CancelledItems',           type: 'float'   }, 
        //{ name: 'CancelledOrders',          type: 'float'   }, 
        //{ name: 'Ticket_1_$',               type: 'float'   },  
        //{ name: 'Ticket_2_$',               type: 'float'   }, 
        //{ name: 'pettycASh1',               type: 'float'   }, 
        //{ name: 'DriveCountLY',             type: 'float'   }, 
        //{ name: 'DriveSalesLY',             type: 'float'   }, 
        //{ name: 'QsVoidTotal',              type: 'float'   }, 
        //{ name: 'QsVoidCount',              type: 'string'  }, 
        //{ name: 'WkDate',                   type: 'string'  }, 
        { name: 'Dep568CreditCardPct',      type: 'float'     }, 
        //{ name: 'Concept4Total',            type: 'float'   }, 
        //{ name: 'PromoDollar1',             type: 'float'   }, 
        //{ name: 'Discount10Amount',         type: 'float'   }, 
        //{ name: 'PromoDollar2',             type: 'float'   }, 
        //{ name: 'PromoDollar4',             type: 'float'   }, 
        { name: 'Dep5678CreditCardPct',     type: 'float'   },   
        //{ name: 'PromoDollar5',             type: 'float'   }, 
        //{ name: 'Dep45CreditCardPct',       type: 'float'   }, 
        //{ name: 'SrDiscount',               type: 'float'   }, 
        //{ name: 'Dep5CreditCardPct',        type: 'float'   }, 
        //{ name: 'Concept1Total',            type: 'float'   }, 
        //{ name: 'Concept1TotalLY',          type: 'float'   }, 
        //{ name: 'Concept2Total',            type: 'float'   }, 
        //{ name: 'Concept2TotalLY',          type: 'float'   }, 
        //{ name: 'MonthName',                type: 'string'  }, 
        //{ name: 'BreakfastCountLy',         type: 'float'   }, 
        //{ name: 'OtherDate',                type: 'string'  }, 
        //{ name: 'GiftCert1Total',           type: 'float'   }, 
        //{ name: 'Refund_T',                 type: 'float'   }, 
        //{ name: 'VISA',                     type: 'float'   }, 
        //{ name: 'GiftCardReload',           type: 'float'   }, 
        //{ name: 'CouponAmount',             type: 'float'   }, 
        //{ name: 'TotalCredCard',            type: 'float'   }, 
        //{ name: 'CredCardNetTax',           type: 'float'   }, 
        //{ name: 'AdjustedSalesDowLy',       type: 'float'   }, 
        { name: 'AdjustedSalesCalcLY',      type: 'float'   }, 
        //{ name: 'FlagSaleCalc',             type: 'float'   }, 
        { name: 'CustomerCountCalcLY',      type: 'int'   }, 
        { name: 'AdjustedSalesCalc2Y',      type: 'float'   }, 
        //{ name: 'FlagSaleCalc2LY',          type: 'float'   }, 
        { name: 'CustomerCountCalc2Y',      type: 'int'   }, 
        { name: 'AdjustedSalesCalcTYvs2Y',  type: 'float'   }, 
        { name: 'CustomerCountCalcTYvs2Y',  type: 'int'   }, 
        //{ name: 'DTSalesCalc',              type: 'float'   }, 
        //{ name: 'DTSalesCalcLY',            type: 'float'   }, 
        //{ name: 'Disc_AmtCoupon',           type: 'float'   }, 
        //{ name: 'Disc_AmtDiscount',         type: 'float'   }, 
        //{ name: 'Disc_10_T',                type: 'float'   }, 
        //{ name: 'CalcPromo',                type: 'float'   }, 
        //{ name: 'CalcBreakfastSalesCY',     type: 'float'   }, 
        //{ name: 'CalcLunchSalesCY',         type: 'float'   }, 
        //{ name: 'CalcAfternoonSalesCY',     type: 'float'   }, 
        //{ name: 'CalcDinnerSalesCY',        type: 'float'   }, 
        //{ name: 'CalcNightSalesCY',         type: 'float'   }, 
        //{ name: 'CalcCloseSalesCY',         type: 'float'   }, 
        //{ name: 'DiscountsDisc',            type: 'float'   }, 
        //{ name: 'DiscountsCoup',            type: 'float'   }, 
        //{ name: 'DiscountsPromo',           type: 'float'   }, 
        //{ name: 'TotalLaborCost',           type: 'float'   },
        
        // --- Not part of the standard set of fields --- //
        { name: 'web_Field1',                   type: 'float'   },
        { name: 'web_Field2',                   type: 'float'   },
        { name: 'web_Field3',                   type: 'float'   },
        { name: 'web_Field4',                   type: 'float'   },           
        { name: 'web_AvgCk',                   type: 'float'   },              
        { name: 'web_DTPercent',               type: 'float'   },          
        { name: 'web_Field8',                  type: 'float'   },             
        { name: 'web_LYDtCountComp',           type: 'float'   },      
        { name: 'web_Field5',                  type: 'float'   },             
        { name: 'web_TjPromoPct',              type: 'float'   },         
        { name: 'web_BFAvgTicket',             type: 'float'   },        
        { name: 'web_BreakfastPercent',        type: 'float'   },   
        { name: 'web_LYBreakfastComp',         type: 'float'   },    
        { name: 'web_LunchSalesPercent',       type: 'float'   },  
        { name: 'web_LYLunchComp',             type: 'float'   },        
        //{ name: '_web_DinnerSalesPct',          type: 'float'   },   
        { name: 'web_LYDayComp',               type: 'float'   },          
        { name: 'web_DinnerSalesPercent',      type: 'float'   }, 
        { name: 'web_LYDinnerComp',            type: 'float'   },       
        { name: 'web_NightSalesPercent',       type: 'float'   },  
        { name: 'web_LYNightComp',             type: 'float'   },        
        { name: 'web_CloseSalesPercent',       type: 'float'   },  
        { name: 'web_LYCloseComp',             type: 'float'   },        
        { name: 'web_LYCloseSalesPercent',     type: 'float'   },
        { name: 'web_Deposite4',           type: 'float'   },      
        { name: 'web_Deposite5',               type: 'int'   },          
        { name: 'web_Deposite6',               type: 'int'   },          
        { name: 'web_Deposite7',               type: 'int'   },          
        { name: 'web_Deposite8',               type: 'int'   }          

    ],
    
    proxy: {
        type: 'ajax',
        //headers: { 'Content-Type': 'application/json;charset=utf-8'},  //This tells ASP.NET to return JSON formatted response
        url: /\/$/g.test(location.href.split('?')[0]) ? "qsoperations.aspx" : "/qsoperations.aspx",
        reader: {
            type: 'json',
            root: 'kpiconcept',
            successProperty: 'success'
        },
        extraParams: {      // Set in controller - example here
            uid: 501,
            sDate: '2011,12,01',
            eDate: '2011,12,07'
        },
        actionMethods: {
            read: 'POST'
        }, 
        timeout: 240000
    }
});
